### ISSUE TITLE
Could not run in docker

### ISSUE THREAD

**Issue by XiaofeiSunUCSF** [ydevs/cellphonedb-docker#1]
I got an error when I try to run the sample code

C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: create pwd/: "pwd/" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'C:\Program Files\Docker\Docker\resources\bin\docker.exe run --help'.

**Comment by XiaofeiSunUCSF** [comment]
docker run --rm --name cellphonedb21 -
it -v ${pwd}/:/root ydevs/cellphonedb:2.1 cellphonedb method statistical_analysis t
est_meta.txt test_counts.txt
Traceback (most recent call last):
  File "/usr/local/bin/cellphonedb", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1064, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 880, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1404, in handle_parse_result
    self.callback, ctx, self, value)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 78, in invoke_param_callback
    return callback(ctx, param, value)
  File "/usr/local/lib/python3.7/site-packages/cellphonedb/src/api_endpoints/terminal_api/util/choose_database.py", line 9, in choose_database
    return DatabaseVersionManager.find_database_for(value)
  File "/usr/local/lib/python3.7/site-packages/cellphonedb/src/database/manager/DatabaseVersionManager.py", line 60, in find_database_for
    _ensure_core_version_in_user_dbs()
  File "/usr/local/lib/python3.7/site-packages/cellphonedb/src/database/manager/DatabaseVersionManager.py", line 46, in _ensure_core_version_in_user_dbs
    os.makedirs(dest_folder, exist_ok=True)
  File "/usr/local/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 1] Operation not permitted: '/root/.cpdb'
